name: PR Reviewer
on:
  pull_request:

jobs:
  Review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.pip
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: /install.sh
    
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10' 
      - name: installations
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run Python script
        run: python src/commenter.py
      - name: Read PR comment from file
        run: cat src/files/output.txt > pr_comment.txt
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: pr_comment.txt
          repo-directory: './'
          requirements-path: 'requirements.txt'
