name: PR Reviewer

on:
  pull_request:

jobs:        
  Review:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    permissions:
      pull-requests: write
    steps:
      - name: Update Conda
        run: conda update -n base -c defaults conda

      - name: Remove existing Conda environment
        run: conda env remove -n base -y

      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: print-diff
        shell: bash
        run: |
          git fetch origin main
          git diff origin/main..HEAD > difference_hunk.txt
          find . -type f -name difference_hunk.txt
          pwd
          echo "difference hunk = "
          cat difference_hunk.txt

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: latest
          conda-channels: conda-forge,pytorch

      - name: Install dependencies
        run: |
          conda activate base
          conda install -c conda-forge nltk
          conda install -c pytorch torchvision torchaudio cudatoolkit=10.2
          conda install -c conda-forge transformers

      - name: Run Python script
        run: python src/commenter.py

      - name: Read PR comment from file
        run: cat src/files/output.txt > pr_comment.txt

      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: pr_comment.txt
          repo-directory: './'
          requirements-path: 'requirements.txt'
