name: PR Reviewer

on:
  pull_request:

jobs:        
  Review:
    runs-on: ubuntu-latest
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: print-diff
        shell: bash
        run: |
          git fetch origin test/CodeBERT
          git diff origin/test/CodeBERT.HEAD > difference_hunk.txt
          find . -type f -name difference_hunk.txt
          pwd
          echo "difference hunk = "
          cat difference_hunk.txt

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nltk
          pip install torch torchvision torchaudio==0.11.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html
          pip install transformers

      - name: Run Python script
        run: python src/commenter.py

      - name: Read PR comment from file
        run: cat src/files/output.txt > pr_comment.txt

      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: pr_comment.txt
          repo-directory: './'
          requirements-path: 'requirements.txt'
