name: PR Reviewer
on:
  pull_request:

jobs:        
  Review:
    runs-on: ubuntu-latest      
    env:
      PR_AUTHOR_GITHUB_ID: ${{ github.event.pull_request.user.login }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Find Github id of PR AUTHOR
        run: |
          echo "PR author: ${PR_AUTHOR_GITHUB_ID}"
      - name: Checkout pull request HEAD
        id: checkout_pr_head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # Check the PR diff using the current branch and the base branch of the PR
      - uses: GrantBirki/git-diff-action@v2.3.0
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: difference_hunk.txt
          file_output_only: "true"

      - name: download llm file
        id: "litllamadownload"
        run: wget https://huggingface.co/msinghC/llm-pr-review/resolve/main/llama-gptq.4bit.pth?download=true -P ${{ github.workspace }}/src/lit_llama/checkpoints/lit-llama/7B


      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.HOME }}/.cache/pip
          key: ${{ runner.os }}-dependencies-${{ hashFiles('requirements.txt') }}-{{ fileset.modifiedTime('requirements.txt') }}
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10' 
      - name: installations
        run: |
          pip install --upgrade pip
          pip install -r requirements-lit-llama.txt
      - name: Run lit-llama Review
        id: "litllama"
        run: |
          cd src/lit_llama
          python generate_review.py --max_new_tokens 10 --temperature 0.8 --top_k 1 --pretrained_path ${{ github.workspace }}/src/lit_llama/checkpoints/lit-llama/7B/llama-gptq.4bit.pth?download=true
        
      - name: Add PR comment
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ${{ github.workspace }}/src/files/output.txt
          repo-directory: './'
          requirements-path: 'requirements.txt'
