name: Static check with mypy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          pip install mypy
      - name: Run Mypy
        run: |
          mypy --strict --ignore-missing-imports src/