name: Static check with mypy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          pip install mypy
      - name: Run Mypy
        run: |
          mypy --strict --ignore-missing-imports src/
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Make lint.sh executable
        run: chmod +x ${{ github.workspace }}/tools/lint.sh

      - name: Run linter
        run: ${{ github.workspace }}/tools/lint.sh
